**Load TensorFlow and Enable Eager Execution**

In [0]:
import tensorflow as tf

In [63]:
tf.__version__

'1.13.1'

In [0]:
tf.enable_eager_execution()

 **1. Read the dataset**

In [0]:
import pandas as pd

In [6]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
data = pd.read_csv('/gdrive/My Drive/Colab Notebooks/bank.csv')

**2. Drop the columns which are unique for all users like IDs (2.5 points)**

In [67]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [68]:
data.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [69]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [0]:
df = data.drop(columns=['RowNumber','CustomerId','Surname'])

In [0]:
df.Geography = pd.Categorical(df.Geography).codes
df.Gender = pd.Categorical(df.Gender).codes

In [72]:
df.head(2)

CreditScore  Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619          0       0   42       2      0.00              1   
1          608          2       0   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0

** 3. Distinguish the feature and target set (2.5 points)**

In [73]:
df.head(2)

CreditScore  Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619          0       0   42       2      0.00              1   
1          608          2       0   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0

In [0]:


x = df.drop(columns='Exited').astype('float32')
y = df["Exited"].astype('float32')

In [0]:

# Converting into One-hot vectors using Keras
from keras.utils import to_categorical
y = to_categorical(y)

In [76]:
y[:2]

array([[0., 1.],
       [1., 0.]], dtype=float32)

** 4. Divide the data set into Train and test sets**

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
# Split the dataset in two equal parts
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=0)

In [79]:
x_train.shape

(8000, 10)

In [80]:
y_train.shape

(8000, 2)

** 5. Normalize the train and test data (2.5 points)**

In [0]:
from sklearn.preprocessing import Normalizer

Normalize = Normalizer()

x_train = Normalize.fit_transform(x_train)

x_test = Normalize.fit_transform(x_test)

In [82]:
x_train[:2]

array([[4.0712436e-03, 1.2207627e-05, 0.0000000e+00, 2.0752967e-04,
        3.0519070e-05, 0.0000000e+00, 1.2207627e-05, 6.1038136e-06,
        0.0000000e+00, 9.9999171e-01],
       [4.5039640e-03, 1.0547925e-05, 1.0547925e-05, 4.4301286e-04,
        1.0547925e-05, 7.9828304e-01, 1.0547925e-05, 1.0547925e-05,
        1.0547925e-05, 6.0226542e-01]], dtype=float32)

In [83]:
y_train[:2]

array([[1., 0.],
       [1., 0.]], dtype=float32)

** 6. Initialize and build the model (10 points)**

In [0]:
#Initialize Sequential model
model_1 = tf.keras.models.Sequential()

#Adding 1st dence layer
model_1.add(tf.keras.layers.Dense(20, activation='sigmoid',input_shape=(10,)))

#Add 2nd hidden layer
model_1.add(tf.keras.layers.Dense(10, activation='sigmoid'))

#Adding OUTPUT layer
model_1.add(tf.keras.layers.Dense(2, activation='softmax'))

In [0]:
#Create optimizer with non-default learning rate
sgd_optimizer1 = tf.keras.optimizers.SGD(lr=0.3)

#Compile the model
model_1.compile(optimizer=sgd_optimizer1, loss='categorical_crossentropy', metrics=['accuracy'])

In [86]:
model_1.fit(x_train,y_train,epochs=10)

Epoch 1/10
8000/8000 [==============================] - 1s 130us/sample - loss: 0.5097 - acc: 0.7960
Epoch 2/10
8000/8000 [==============================] - 1s 120us/sample - loss: 0.5090 - acc: 0.7960
Epoch 3/10
8000/8000 [==============================] - 1s 127us/sample - loss: 0.5074 - acc: 0.7960
Epoch 4/10
8000/8000 [==============================] - 1s 130us/sample - loss: 0.5075 - acc: 0.7960
Epoch 5/10
8000/8000 [==============================] - 1s 133us/sample - loss: 0.5054 - acc: 0.7960
Epoch 6/10
8000/8000 [==============================] - 1s 130us/sample - loss: 0.5033 - acc: 0.7960
Epoch 7/10
8000/8000 [==============================] - 1s 132us/sample - loss: 0.5029 - acc: 0.7960
Epoch 8/10
8000/8000 [==============================] - 1s 132us/sample - loss: 0.5038 - acc: 0.7960
Epoch 9/10
8000/8000 [==============================] - 1s 128us/sample - loss: 0.5029 - acc: 0.7960
Epoch 10/10
8000/8000 [==============================] - 1s 131us/sample - loss: 0.5022 - a

**9. Predict the results using 0.5 as a threshold (5 points)**

In [0]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [0]:
y_test_predict = model_1.predict(x_test)
y_test_predict = y_test_predict.argmax(axis=1)

In [0]:
y_test_predict = (model_1.predict_proba(x_test)[:,1] >= 0.5).astype('float32')

In [90]:
y_test_predict

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

**10. Print the Accuracy score and confusion matrix (2.5 points)**

In [0]:
y_test = y_test.argmax(axis=1)

In [93]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [0]:
accuracy = accuracy_score(y_test,y_test_predict)

In [95]:
print("The test accuracy percentage is :", accuracy*100 )

The test accuracy percentage is : 79.75


In [96]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_test_predict)

array([[1595,    0],
       [ 405,    0]])