### Load tensorflow

In [0]:
import tensorflow as tf

In [0]:
from sklearn.preprocessing import Normalizer

### Collect Data

In [0]:
import pandas as pd

In [0]:
def mount_drive(filename):
  from google.colab import drive
  drive.mount('/gdrive/')
  data = pd.read_csv('/gdrive/My Drive/Colab Notebooks/' + filename)
  return data

In [29]:
data =mount_drive("prices.csv")

Drive already mounted at /gdrive/; to attempt to forcibly remount, call drive.mount("/gdrive/", force_remount=True).


### Check all columns in the dataset

In [30]:
data.dtypes

date       object
symbol     object
open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

In [31]:
data.shape

(851264, 7)

In [32]:
data.describe()

open          close            low           high  \
count  851264.000000  851264.000000  851264.000000  851264.000000   
mean       70.836986      70.857109      70.118414      71.543476   
std        83.695876      83.689686      82.877294      84.465504   
min         0.850000       0.860000       0.830000       0.880000   
25%        33.840000      33.849998      33.480000      34.189999   
50%        52.770000      52.799999      52.230000      53.310001   
75%        79.879997      79.889999      79.110001      80.610001   
max      1584.439941    1578.130005    1549.939941    1600.930054   

             volume  
count  8.512640e+05  
mean   5.415113e+06  
std    1.249468e+07  
min    0.000000e+00  
25%    1.221500e+06  
50%    2.476250e+06  
75%    5.222500e+06  
max    8.596434e+08

### Drop columns `date` and  `symbol`

In [0]:
data.drop(columns=['date','symbol'],axis=1,inplace=True)

### Consider only first 1000 rows in the dataset for building feature set and target set

In [0]:
data = data.head(1000)

In [35]:
data.shape

(1000, 5)

In [36]:
data.sample(5)

open       close         low        high      volume
174  124.000000  123.089996  122.860001  124.050003    488900.0
558   66.059998   65.349998   65.120003   66.070000  11972400.0
443   20.730000   20.540001   20.450001   20.730000   9185600.0
960    5.880000    6.170000    5.880000    6.190000  16660800.0
851   35.060001   34.849998   34.209999   35.070000   2735200.0

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split

X1 = data.drop(columns= "close" , axis = 1) 
Y1 = data["close"]
transformer = Normalizer()
X1= transformer.fit_transform(X1)

train_x, test_x,train_y,test_y = train_test_split(X1, Y1, test_size=.3, random_state=7)




## Building the graph in tensorflow

1.Define input data placeholders

In [0]:
X = tf.placeholder(dtype=tf.float32, shape=[None, 4])
Y = tf.placeholder(dtype=tf.float32, shape=[None])

2.Define Weights and Bias

In [0]:
w = tf.Variable(tf.zeros(shape=[4,1],dtype="float32"))
b = tf.Variable(tf.zeros(shape=(1),dtype="float32"))

3.Prediction

In [0]:
out = tf.add(tf.matmul(X, w), b)

4.Loss (Cost) Function [Mean square error]

In [0]:
mse = tf.reduce_mean(tf.squared_difference(out, Y))

5.GradientDescent Optimizer to minimize Loss [GradientDescentOptimizer]

In [0]:
opt=tf.train.GradientDescentOptimizer(0.01).minimize(mse)


## Execute the Graph for 100 epochs and observe the loss

In [0]:
net = tf.Session()
net.run(tf.global_variables_initializer())

In [48]:

for i in range(100):
    _,loss = net.run([opt,mse], feed_dict={X: train_x, Y: train_y})
    print('Current Loss on iteration',i,loss)

('Current Loss on iteration', 0, 8370.582)
('Current Loss on iteration', 1, 8002.651)
('Current Loss on iteration', 2, 7663.5664)
('Current Loss on iteration', 3, 7351.0664)
('Current Loss on iteration', 4, 7063.0654)
('Current Loss on iteration', 5, 6797.644)
('Current Loss on iteration', 6, 6553.032)
('Current Loss on iteration', 7, 6327.598)
('Current Loss on iteration', 8, 6119.837)
('Current Loss on iteration', 9, 5928.3643)
('Current Loss on iteration', 10, 5751.904)
('Current Loss on iteration', 11, 5589.2773)
('Current Loss on iteration', 12, 5439.4014)
('Current Loss on iteration', 13, 5301.2754)
('Current Loss on iteration', 14, 5173.9785)
('Current Loss on iteration', 15, 5056.6616)
('Current Loss on iteration', 16, 4948.5425)
('Current Loss on iteration', 17, 4848.9004)
('Current Loss on iteration', 18, 4757.069)
('Current Loss on iteration', 19, 4672.4375)
('Current Loss on iteration', 20, 4594.442)
('Current Loss on iteration', 21, 4522.5605)
('Current Loss on iteration',

### Get the shapes and values of W and b

Hint: Use sess.run(W) to get W.

In [67]:
net.run(w).shape

(4, 1)

In [68]:
net.run(w)

array([[2.5353238e-03],
       [2.5108382e-03],
       [2.5564777e-03],
       [3.3674850e+01]], dtype=float32)

In [69]:
net.run(b).shape

(1,)

In [70]:
net.run(b)

array([33.674854], dtype=float32)

In [0]:
net.close()

### Linear Classification using Keras

### Building the simple Neural Network in Keras with one neuron in the dense hidden layer.
#### Use Mean square error as loss function and sgd as optimizer

In [49]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(1,  input_shape=(4,)))


### Execute the model

In [0]:
model.compile(optimizer='sgd', loss='mean_squared_error')


In [0]:
from sklearn.model_selection import train_test_split

X1 = data.drop(columns= "close" , axis = 1) 
Y1 = data["close"]
transformer = Normalizer()
X1= transformer.fit_transform(X1)

train_x, test_x,train_y,test_y = train_test_split(X1, Y1, test_size=.3, random_state=7)


In [72]:
model.fit(train_x,train_y, epochs=100)

Epoch 1/100
700/700 [==============================] - 0s 91us/sample - loss: nan
Epoch 2/100
700/700 [==============================] - 0s 82us/sample - loss: nan
Epoch 3/100
700/700 [==============================] - 0s 78us/sample - loss: nan
Epoch 4/100
700/700 [==============================] - 0s 109us/sample - loss: nan
Epoch 5/100
700/700 [==============================] - 0s 86us/sample - loss: nan
Epoch 6/100
700/700 [==============================] - 0s 90us/sample - loss: nan
Epoch 7/100
700/700 [==============================] - 0s 79us/sample - loss: nan
Epoch 8/100
700/700 [==============================] - 0s 78us/sample - loss: nan
Epoch 9/100
700/700 [==============================] - 0s 81us/sample - loss: nan
Epoch 10/100
700/700 [==============================] - 0s 78us/sample - loss: nan
Epoch 11/100
700/700 [==============================] - 0s 74us/sample - loss: nan
Epoch 12/100
700/700 [==============================] - 0s 80us/sample - loss: nan
Epoch 13/100

In [123]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_v1_6 (Ba multiple                  16        
_________________________________________________________________
dense (Dense)                multiple                  5         
Total params: 21
Trainable params: 13
Non-trainable params: 8
_________________________________________________________________


### Classification using Keras 

### Load the given Iris data using pandas (Iris.csv)

In [73]:
iris= mount_drive("Iris-1.csv")

Drive already mounted at /gdrive/; to attempt to forcibly remount, call drive.mount("/gdrive/", force_remount=True).


In [74]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [75]:
iris.head(3)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [0]:
iris["Species"] = pd.Categorical(iris["Species"]).codes

In [0]:
iris.drop("Id",axis=1,inplace=True)

### Splitting the data into feature set and target set

In [0]:
features = iris.drop(columns= ['Species']) 

target = iris[['Species']]


In [79]:
features.head(2)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2

In [80]:
target.head(2)

Species
0        0
1        0

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

### Divide the dataset into Training and test (70:30)

In [0]:
from sklearn.model_selection import train_test_split
transformer = Normalizer()
#features = transformer.fit_transform(features)

train_x, test_x,train_y,test_y = train_test_split(features, target, test_size=.3, random_state=7)

### Model
Build the model with following layers: <br>
1. First dense layer with 10 neurons with input shape 4 (according to the feature set) <br>
2. Second Dense layer with 8 neurons <br>
3. Output layer with 3 neurons with softmax activation (output layer, 3 neurons as we have 3 classes) <br>
4. Use SGD and categorical_crossentropy loss 

In [0]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.BatchNormalization())

model.add(tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))

#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)

#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

### Fitting the model and predicting 

In [93]:

#train model
model.fit(features.values, target.values, validation_split=0.2, epochs=30)

Train on 120 samples, validate on 30 samples
Epoch 1/30
120/120 [==============================] - 0s 2ms/sample - loss: 2.6806 - acc: 0.3917 - val_loss: 7.6843 - val_acc: 1.0000
Epoch 2/30
120/120 [==============================] - 0s 235us/sample - loss: 2.5675 - acc: 0.4083 - val_loss: 7.3417 - val_acc: 1.0000
Epoch 3/30
120/120 [==============================] - 0s 223us/sample - loss: 2.5318 - acc: 0.3500 - val_loss: 7.1432 - val_acc: 1.0000
Epoch 4/30
120/120 [==============================] - 0s 179us/sample - loss: 2.5153 - acc: 0.3000 - val_loss: 7.0140 - val_acc: 1.0000
Epoch 5/30
120/120 [==============================] - 0s 173us/sample - loss: 2.5032 - acc: 0.2333 - val_loss: 6.9226 - val_acc: 1.0000
Epoch 6/30
120/120 [==============================] - 0s 170us/sample - loss: 2.5021 - acc: 0.1667 - val_loss: 6.8611 - val_acc: 1.0000
Epoch 7/30
120/120 [==============================] - 0s 171us/sample - loss: 2.4952 - acc: 0.1583 - val_loss: 6.8173 - val_acc: 1.0000
Epoch

### Report Accuracy of the predicted values

In [95]:
model.predict(test_x)

array([[0.3343727 , 0.43701422, 0.22861305],
       [0.33349967, 0.433953  , 0.23254739],
       [0.32862708, 0.44214615, 0.22922678],
       [0.33403537, 0.4346533 , 0.23131132],
       [0.33396378, 0.43791428, 0.22812201],
       [0.33015946, 0.46877983, 0.20106064],
       [0.33620426, 0.44070452, 0.22309113],
       [0.33562982, 0.43675336, 0.22761692],
       [0.32896104, 0.43865204, 0.23238684],
       [0.33520356, 0.43550295, 0.22929351],
       [0.3362234 , 0.43909207, 0.22468455],
       [0.3333023 , 0.43262458, 0.23407312],
       [0.3275916 , 0.43213642, 0.240272  ],
       [0.3341896 , 0.4380413 , 0.22776908],
       [0.32892352, 0.45042276, 0.22065373],
       [0.33361825, 0.43485394, 0.23152778],
       [0.33741942, 0.44451487, 0.2180657 ],
       [0.33506873, 0.43801516, 0.22691616],
       [0.32838598, 0.43483368, 0.23678036],
       [0.32923546, 0.4531838 , 0.21758074],
       [0.33566594, 0.4410934 , 0.22324064],
       [0.33504993, 0.43982545, 0.22512458],
       [0.